=begin
#Spinnaker API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.7

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::AmazonInfrastructureControllerApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AmazonInfrastructureControllerApi' do
  before do
    # run before each test
    @instance = SwaggerClient::AmazonInfrastructureControllerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AmazonInfrastructureControllerApi' do
    it 'should create an instance of AmazonInfrastructureControllerApi' do
      expect(@instance).to be_instance_of(SwaggerClient::AmazonInfrastructureControllerApi)
    end
  end

  # unit tests for instance_types_using_get
  # Get instance types
  # @param [Hash] opts the optional parameters
  # @return [Array<Object>]
  describe 'instance_types_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for subnets_using_get
  # Get subnets
  # @param [Hash] opts the optional parameters
  # @return [Array<Object>]
  describe 'subnets_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for vpcs_using_get
  # Get VPCs
  # @param [Hash] opts the optional parameters
  # @return [Array<Object>]
  describe 'vpcs_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
