=begin
#Spinnaker API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.7

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::ApplicationControllerApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ApplicationControllerApi' do
  before do
    # run before each test
    @instance = SwaggerClient::ApplicationControllerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ApplicationControllerApi' do
    it 'should create an instance of ApplicationControllerApi' do
      expect(@instance).to be_instance_of(SwaggerClient::ApplicationControllerApi)
    end
  end

  # unit tests for cancel_pipeline_using_put
  # Cancel pipeline
  # @param id id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :reason reason
  # @return [Hash<String, Object>]
  describe 'cancel_pipeline_using_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for cancel_task_using_put
  # Cancel task
  # @param id id
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, Object>]
  describe 'cancel_task_using_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_all_applications_using_get
  # Retrieve a list of applications
  # @param [Hash] opts the optional parameters
  # @option opts [String] :account filters results to only include applications deployed in the specified account
  # @option opts [String] :owner filteres results to only include applications owned by the specified email
  # @return [Array<Object>]
  describe 'get_all_applications_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_application_history_using_get
  # Retrieve a list of an application&#39;s configuration revision history
  # @param application application
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit limit
  # @return [Array<Object>]
  describe 'get_application_history_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_application_using_get
  # Retrieve an application&#39;s details
  # @param application application
  # @param [Hash] opts the optional parameters
  # @option opts [BOOLEAN] :expand expand
  # @return [Hash<String, Object>]
  describe 'get_application_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_pipeline_config_using_get
  # Retrieve a pipeline configuration
  # @param application application
  # @param pipeline_name pipelineName
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, Object>]
  describe 'get_pipeline_config_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_pipeline_configs_for_application_using_get
  # Retrieve a list of an application&#39;s pipeline configurations
  # @param application application
  # @param [Hash] opts the optional parameters
  # @return [Array<Object>]
  describe 'get_pipeline_configs_for_application_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_pipelines_using_get
  # Retrieve a list of an application&#39;s pipeline executions
  # @param application application
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit limit
  # @option opts [String] :statuses statuses
  # @option opts [BOOLEAN] :expand expand
  # @return [Array<Object>]
  describe 'get_pipelines_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_strategy_config_using_get
  # Retrieve a pipeline strategy configuration
  # @param application application
  # @param strategy_name strategyName
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, Object>]
  describe 'get_strategy_config_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_strategy_configs_for_application_using_get
  # Retrieve a list of an application&#39;s pipeline strategy configurations
  # @param application application
  # @param [Hash] opts the optional parameters
  # @return [Array<Object>]
  describe 'get_strategy_configs_for_application_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_task_details_using_get
  # Get task details
  # @param id id
  # @param task_details_id taskDetailsId
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_rate_limit_app X-RateLimit-App
  # @return [Hash<String, Object>]
  describe 'get_task_details_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_task_using_get
  # Get task
  # @param id id
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, Object>]
  describe 'get_task_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_tasks_using_get
  # Retrieve a list of an application&#39;s tasks
  # @param application application
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page page
  # @option opts [Integer] :limit limit
  # @option opts [String] :statuses statuses
  # @return [Array<Object>]
  describe 'get_tasks_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for invoke_pipeline_config_using_post
  # Invoke pipeline config
  # @param application application
  # @param pipeline_name pipelineName
  # @param [Hash] opts the optional parameters
  # @option opts [Object] :trigger trigger
  # @option opts [String] :user user
  # @return [HttpEntity]
  describe 'invoke_pipeline_config_using_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for task_using_post
  # Create task
  # @param application application
  # @param map map
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, Object>]
  describe 'task_using_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
