=begin
#Spinnaker API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.7

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::ArtifactControllerApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ArtifactControllerApi' do
  before do
    # run before each test
    @instance = SwaggerClient::ArtifactControllerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ArtifactControllerApi' do
    it 'should create an instance of ArtifactControllerApi' do
      expect(@instance).to be_instance_of(SwaggerClient::ArtifactControllerApi)
    end
  end

  # unit tests for all_using_get
  # Retrieve the list of artifact accounts configured in Clouddriver.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_rate_limit_app X-RateLimit-App
  # @return [Array<Object>]
  describe 'all_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for artifact_versions_using_get
  # Retrieve the list of artifact versions by account and artifact names
  # @param account_name accountName
  # @param type type
  # @param artifact_name artifactName
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_rate_limit_app X-RateLimit-App
  # @return [Array<String>]
  describe 'artifact_versions_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
