=begin
#Spinnaker API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.7

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::BakeControllerApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'BakeControllerApi' do
  before do
    # run before each test
    @instance = SwaggerClient::BakeControllerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BakeControllerApi' do
    it 'should create an instance of BakeControllerApi' do
      expect(@instance).to be_instance_of(SwaggerClient::BakeControllerApi)
    end
  end

  # unit tests for bake_options_using_get
  # Retrieve a list of available bakery base images for a given cloud provider
  # @param cloud_provider cloudProvider
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'bake_options_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for bake_options_using_get1
  # Retrieve a list of available bakery base images, grouped by cloud provider
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'bake_options_using_get1 test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for lookup_logs_using_get
  # Retrieve the logs for a given bake
  # @param region region
  # @param status_id statusId
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'lookup_logs_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
