=begin
#Spinnaker API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.7

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::BuildControllerApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'BuildControllerApi' do
  before do
    # run before each test
    @instance = SwaggerClient::BuildControllerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BuildControllerApi' do
    it 'should create an instance of BuildControllerApi' do
      expect(@instance).to be_instance_of(SwaggerClient::BuildControllerApi)
    end
  end

  # unit tests for get_build_masters_using_get
  # Get build masters
  # Deprecated, use the v3 endpoint instead
  # @param type type
  # @param [Hash] opts the optional parameters
  # @return [Array<Object>]
  describe 'get_build_masters_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_build_using_get
  # Get build for build master
  # Deprecated, use the v3 endpoint instead
  # @param build_master buildMaster
  # @param number number
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, Object>]
  describe 'get_build_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_builds_using_get
  # Get builds for build master
  # Deprecated, use the v3 endpoint instead
  # @param build_master buildMaster
  # @param [Hash] opts the optional parameters
  # @return [Array<Object>]
  describe 'get_builds_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_job_config_using_get
  # Get job config
  # Deprecated, use the v3 endpoint instead
  # @param build_master buildMaster
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, Object>]
  describe 'get_job_config_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_jobs_for_build_master_using_get
  # Get jobs for build master
  # Deprecated, use the v3 endpoint instead
  # @param build_master buildMaster
  # @param [Hash] opts the optional parameters
  # @return [Array<Object>]
  describe 'get_jobs_for_build_master_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v3_get_build_masters_using_get
  # Get build masters
  # @param type type
  # @param [Hash] opts the optional parameters
  # @return [Array<Object>]
  describe 'v3_get_build_masters_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v3_get_build_using_get
  # Get build for build master
  # @param build_master buildMaster
  # @param number number
  # @param job job
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, Object>]
  describe 'v3_get_build_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v3_get_builds_using_get
  # Get builds for build master
  # @param build_master buildMaster
  # @param job job
  # @param [Hash] opts the optional parameters
  # @return [Array<Object>]
  describe 'v3_get_builds_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v3_get_job_config_using_get
  # Get job config
  # @param build_master buildMaster
  # @param job job
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, Object>]
  describe 'v3_get_job_config_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v3_get_jobs_for_build_master_using_get
  # Get jobs for build master
  # @param build_master buildMaster
  # @param [Hash] opts the optional parameters
  # @return [Array<Object>]
  describe 'v3_get_jobs_for_build_master_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
