=begin
#Spinnaker API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.7

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::ImageControllerApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ImageControllerApi' do
  before do
    # run before each test
    @instance = SwaggerClient::ImageControllerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ImageControllerApi' do
    it 'should create an instance of ImageControllerApi' do
      expect(@instance).to be_instance_of(SwaggerClient::ImageControllerApi)
    end
  end

  # unit tests for find_images_using_get
  # Retrieve a list of images, filtered by cloud provider, region, and account
  # The query parameter &#x60;q&#x60; filters the list of images by image name
  # @param [Hash] opts the optional parameters
  # @option opts [String] :provider provider
  # @option opts [String] :q q
  # @option opts [String] :region region
  # @option opts [String] :account account
  # @option opts [Integer] :count count
  # @return [Array<Object>]
  describe 'find_images_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_tags_using_get
  # Find tags
  # @param account account
  # @param repository repository
  # @param [Hash] opts the optional parameters
  # @option opts [String] :provider provider
  # @option opts [String] :x_rate_limit_app X-RateLimit-App
  # @return [Array<Object>]
  describe 'find_tags_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_image_details_using_get
  # Get image details
  # @param account account
  # @param region region
  # @param image_id imageId
  # @param [Hash] opts the optional parameters
  # @option opts [String] :provider provider
  # @option opts [String] :x_rate_limit_app X-RateLimit-App
  # @return [Array<Object>]
  describe 'get_image_details_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
