=begin
#Spinnaker API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.7

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::InstanceControllerApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'InstanceControllerApi' do
  before do
    # run before each test
    @instance = SwaggerClient::InstanceControllerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InstanceControllerApi' do
    it 'should create an instance of InstanceControllerApi' do
      expect(@instance).to be_instance_of(SwaggerClient::InstanceControllerApi)
    end
  end

  # unit tests for get_console_output_using_get
  # Retrieve an instance&#39;s console output
  # @param account account
  # @param region region
  # @param instance_id instanceId
  # @param [Hash] opts the optional parameters
  # @option opts [String] :provider provider
  # @option opts [String] :x_rate_limit_app X-RateLimit-App
  # @return [Object]
  describe 'get_console_output_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_instance_details_using_get
  # Retrieve an instance&#39;s details
  # @param account account
  # @param region region
  # @param instance_id instanceId
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_rate_limit_app X-RateLimit-App
  # @return [Object]
  describe 'get_instance_details_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
