=begin
#Spinnaker API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.7

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::JobControllerApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'JobControllerApi' do
  before do
    # run before each test
    @instance = SwaggerClient::JobControllerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of JobControllerApi' do
    it 'should create an instance of JobControllerApi' do
      expect(@instance).to be_instance_of(SwaggerClient::JobControllerApi)
    end
  end

  # unit tests for get_job_using_get
  # Get job
  # @param application_name applicationName
  # @param account account
  # @param region region
  # @param name name
  # @param [Hash] opts the optional parameters
  # @option opts [String] :expand expand
  # @option opts [String] :x_rate_limit_app X-RateLimit-App
  # @return [Hash<String, Object>]
  describe 'get_job_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
