=begin
#Spinnaker API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.7

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::NetworkControllerApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'NetworkControllerApi' do
  before do
    # run before each test
    @instance = SwaggerClient::NetworkControllerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of NetworkControllerApi' do
    it 'should create an instance of NetworkControllerApi' do
      expect(@instance).to be_instance_of(SwaggerClient::NetworkControllerApi)
    end
  end

  # unit tests for all_by_cloud_provider_using_get
  # Retrieve a list of networks for a given cloud provider
  # @param cloud_provider cloudProvider
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_rate_limit_app X-RateLimit-App
  # @return [Array<Object>]
  describe 'all_by_cloud_provider_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for all_using_get2
  # Retrieve a list of networks, grouped by cloud provider
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_rate_limit_app X-RateLimit-App
  # @return [Hash<String, Object>]
  describe 'all_using_get2 test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
