=begin
#Spinnaker API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.7

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::PipelineConfigControllerApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PipelineConfigControllerApi' do
  before do
    # run before each test
    @instance = SwaggerClient::PipelineConfigControllerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PipelineConfigControllerApi' do
    it 'should create an instance of PipelineConfigControllerApi' do
      expect(@instance).to be_instance_of(SwaggerClient::PipelineConfigControllerApi)
    end
  end

  # unit tests for convert_pipeline_config_to_pipeline_template_using_get
  # Convert a pipeline config to a pipeline template.
  # @param pipeline_config_id pipelineConfigId
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'convert_pipeline_config_to_pipeline_template_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_all_pipeline_configs_using_get
  # Get all pipeline configs.
  # @param [Hash] opts the optional parameters
  # @return [Array<Object>]
  describe 'get_all_pipeline_configs_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_pipeline_config_history_using_get
  # Get pipeline config history.
  # @param pipeline_config_id pipelineConfigId
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit limit
  # @return [Array<Object>]
  describe 'get_pipeline_config_history_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
