=begin
#Spinnaker API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.7

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::ProjectControllerApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ProjectControllerApi' do
  before do
    # run before each test
    @instance = SwaggerClient::ProjectControllerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProjectControllerApi' do
    it 'should create an instance of ProjectControllerApi' do
      expect(@instance).to be_instance_of(SwaggerClient::ProjectControllerApi)
    end
  end

  # unit tests for all_pipelines_for_project_using_get
  # Get all pipelines for project
  # @param id id
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit limit
  # @option opts [String] :statuses statuses
  # @return [Array<Object>]
  describe 'all_pipelines_for_project_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for all_using_get3
  # Get all projects
  # @param [Hash] opts the optional parameters
  # @return [Array<Object>]
  describe 'all_using_get3 test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_clusters_using_get3
  # Get a project&#39;s clusters
  # @param id id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_rate_limit_app X-RateLimit-App
  # @return [Array<Object>]
  describe 'get_clusters_using_get3 test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_using_get1
  # Get a project
  # @param id id
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, Object>]
  describe 'get_using_get1 test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
