=begin
#Spinnaker API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.7

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::ReorderPipelinesControllerApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ReorderPipelinesControllerApi' do
  before do
    # run before each test
    @instance = SwaggerClient::ReorderPipelinesControllerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ReorderPipelinesControllerApi' do
    it 'should create an instance of ReorderPipelinesControllerApi' do
      expect(@instance).to be_instance_of(SwaggerClient::ReorderPipelinesControllerApi)
    end
  end

  # unit tests for reorder_pipelines_using_post
  # Re-order pipelines
  # @param reorder_pipelines_command reorderPipelinesCommand
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'reorder_pipelines_using_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
