=begin
#Spinnaker API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.7

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::SearchControllerApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SearchControllerApi' do
  before do
    # run before each test
    @instance = SwaggerClient::SearchControllerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SearchControllerApi' do
    it 'should create an instance of SearchControllerApi' do
      expect(@instance).to be_instance_of(SwaggerClient::SearchControllerApi)
    end
  end

  # unit tests for search_using_get
  # Search infrastructure
  # @param type type
  # @param [Hash] opts the optional parameters
  # @option opts [String] :q q
  # @option opts [String] :platform platform
  # @option opts [Integer] :page_size pageSize
  # @option opts [Integer] :page page
  # @option opts [BOOLEAN] :allow_short_query allowShortQuery
  # @option opts [String] :x_rate_limit_app X-RateLimit-App
  # @return [Array<Object>]
  describe 'search_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
