=begin
#Spinnaker API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.7

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::ServerGroupControllerApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ServerGroupControllerApi' do
  before do
    # run before each test
    @instance = SwaggerClient::ServerGroupControllerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ServerGroupControllerApi' do
    it 'should create an instance of ServerGroupControllerApi' do
      expect(@instance).to be_instance_of(SwaggerClient::ServerGroupControllerApi)
    end
  end

  # unit tests for get_server_group_details_using_get
  # Retrieve a server group&#39;s details
  # @param application_name applicationName
  # @param account account
  # @param region region
  # @param server_group_name serverGroupName
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_rate_limit_app X-RateLimit-App
  # @option opts [String] :include_details includeDetails
  # @return [Object]
  describe 'get_server_group_details_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_server_groups_for_application_using_get
  # Retrieve a list of server groups for a given application
  # @param application_name applicationName
  # @param [Hash] opts the optional parameters
  # @option opts [String] :expand expand
  # @option opts [String] :cloud_provider cloudProvider
  # @option opts [String] :clusters clusters
  # @option opts [String] :x_rate_limit_app X-RateLimit-App
  # @return [Array<Object>]
  describe 'get_server_groups_for_application_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
