=begin
#Spinnaker API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.7

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::ServerGroupManagerControllerApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ServerGroupManagerControllerApi' do
  before do
    # run before each test
    @instance = SwaggerClient::ServerGroupManagerControllerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ServerGroupManagerControllerApi' do
    it 'should create an instance of ServerGroupManagerControllerApi' do
      expect(@instance).to be_instance_of(SwaggerClient::ServerGroupManagerControllerApi)
    end
  end

  # unit tests for get_server_group_managers_for_application_using_get
  # Retrieve a list of server group managers for an application
  # @param application application
  # @param [Hash] opts the optional parameters
  # @return [Array<Object>]
  describe 'get_server_group_managers_for_application_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
