=begin
#Spinnaker API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.7

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::SnapshotControllerApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SnapshotControllerApi' do
  before do
    # run before each test
    @instance = SwaggerClient::SnapshotControllerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SnapshotControllerApi' do
    it 'should create an instance of SnapshotControllerApi' do
      expect(@instance).to be_instance_of(SwaggerClient::SnapshotControllerApi)
    end
  end

  # unit tests for get_current_snapshot_using_get
  # Get current snapshot
  # @param application application
  # @param account account
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, Object>]
  describe 'get_current_snapshot_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_snapshot_history_using_get
  # Get snapshot history
  # @param application application
  # @param account account
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit limit
  # @return [Array<Object>]
  describe 'get_snapshot_history_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
