=begin
#Spinnaker API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.7

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::SubnetControllerApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SubnetControllerApi' do
  before do
    # run before each test
    @instance = SwaggerClient::SubnetControllerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SubnetControllerApi' do
    it 'should create an instance of SubnetControllerApi' do
      expect(@instance).to be_instance_of(SwaggerClient::SubnetControllerApi)
    end
  end

  # unit tests for all_by_cloud_provider_using_get1
  # Retrieve a list of subnets for a given cloud provider
  # @param cloud_provider cloudProvider
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_rate_limit_app X-RateLimit-App
  # @return [Array<Object>]
  describe 'all_by_cloud_provider_using_get1 test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
