=begin
#Spinnaker API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.7

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::V2PipelineTemplatesControllerApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'V2PipelineTemplatesControllerApi' do
  before do
    # run before each test
    @instance = SwaggerClient::V2PipelineTemplatesControllerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of V2PipelineTemplatesControllerApi' do
    it 'should create an instance of V2PipelineTemplatesControllerApi' do
      expect(@instance).to be_instance_of(SwaggerClient::V2PipelineTemplatesControllerApi)
    end
  end

  # unit tests for create_using_post1
  # (ALPHA) Create a pipeline template.
  # @param pipeline_template pipelineTemplate
  # @param [Hash] opts the optional parameters
  # @option opts [String] :tag tag
  # @return [nil]
  describe 'create_using_post1 test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_using_delete1
  # Delete a pipeline template.
  # @param id id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :tag tag
  # @option opts [String] :digest digest
  # @option opts [String] :application application
  # @return [Hash<String, Object>]
  describe 'delete_using_delete1 test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_using_get2
  # (ALPHA) Get a pipeline template.
  # @param id id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :tag tag
  # @option opts [String] :digest digest
  # @return [Hash<String, Object>]
  describe 'get_using_get2 test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_pipeline_template_dependents_using_get1
  # (ALPHA) List all pipelines that implement a pipeline template
  # @param id id
  # @param [Hash] opts the optional parameters
  # @return [Array<Object>]
  describe 'list_pipeline_template_dependents_using_get1 test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_using_get1
  # (ALPHA) List pipeline templates.
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :scopes scopes
  # @return [Array<Object>]
  describe 'list_using_get1 test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for plan_using_post
  # (ALPHA) Plan a pipeline template configuration.
  # @param pipeline pipeline
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, Object>]
  describe 'plan_using_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_using_post1
  # (ALPHA) Update a pipeline template.
  # @param id id
  # @param pipeline_template pipelineTemplate
  # @param [Hash] opts the optional parameters
  # @option opts [String] :tag tag
  # @option opts [BOOLEAN] :skip_plan_dependents skipPlanDependents
  # @return [nil]
  describe 'update_using_post1 test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
