=begin
#Spinnaker API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.7

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::WebhookControllerApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'WebhookControllerApi' do
  before do
    # run before each test
    @instance = SwaggerClient::WebhookControllerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WebhookControllerApi' do
    it 'should create an instance of WebhookControllerApi' do
      expect(@instance).to be_instance_of(SwaggerClient::WebhookControllerApi)
    end
  end

  # unit tests for preconfigured_webhooks_using_get
  # Retrieve a list of preconfigured webhooks in Orca
  # @param [Hash] opts the optional parameters
  # @return [Array<Object>]
  describe 'preconfigured_webhooks_using_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for webhooks_using_post
  # Endpoint for posting webhooks to Spinnaker&#39;s webhook service
  # @param type type
  # @param source source
  # @param [Hash] opts the optional parameters
  # @option opts [Object] :event event
  # @option opts [String] :x_hub_signature X-Hub-Signature
  # @option opts [String] :x_event_key X-Event-Key
  # @return [Object]
  describe 'webhooks_using_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
