=begin
#Spinnaker API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.7

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::GrantedAuthority
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'GrantedAuthority' do
  before do
    # run before each test
    @instance = SwaggerClient::GrantedAuthority.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GrantedAuthority' do
    it 'should create an instance of GrantedAuthority' do
      expect(@instance).to be_instance_of(SwaggerClient::GrantedAuthority)
    end
  end
  describe 'test attribute "authority"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
