=begin
#Spinnaker API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.7

=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
require 'swagger_client/models/account'
require 'swagger_client/models/account_details'
require 'swagger_client/models/granted_authority'
require 'swagger_client/models/hash_mapstringobject'
require 'swagger_client/models/http_entity'
require 'swagger_client/models/mapstringstring'
require 'swagger_client/models/pipeline_template_dependent'
require 'swagger_client/models/reorder_pipelines_command'
require 'swagger_client/models/response_entity'
require 'swagger_client/models/user'
require 'swagger_client/models/version'

# APIs
require 'swagger_client/api/amazon_infrastructure_controller_api'
require 'swagger_client/api/application_controller_api'
require 'swagger_client/api/artifact_controller_api'
require 'swagger_client/api/auth_controller_api'
require 'swagger_client/api/bake_controller_api'
require 'swagger_client/api/build_controller_api'
require 'swagger_client/api/cluster_controller_api'
require 'swagger_client/api/concourse_controller_api'
require 'swagger_client/api/credentials_controller_api'
require 'swagger_client/api/ecs_server_group_events_controller_api'
require 'swagger_client/api/executions_controller_api'
require 'swagger_client/api/firewall_controller_api'
require 'swagger_client/api/image_controller_api'
require 'swagger_client/api/instance_controller_api'
require 'swagger_client/api/job_controller_api'
require 'swagger_client/api/load_balancer_controller_api'
require 'swagger_client/api/network_controller_api'
require 'swagger_client/api/pipeline_config_controller_api'
require 'swagger_client/api/pipeline_controller_api'
require 'swagger_client/api/pipeline_templates_controller_api'
require 'swagger_client/api/project_controller_api'
require 'swagger_client/api/pubsub_subscription_controller_api'
require 'swagger_client/api/reorder_pipelines_controller_api'
require 'swagger_client/api/search_controller_api'
require 'swagger_client/api/security_group_controller_api'
require 'swagger_client/api/server_group_controller_api'
require 'swagger_client/api/server_group_manager_controller_api'
require 'swagger_client/api/snapshot_controller_api'
require 'swagger_client/api/subnet_controller_api'
require 'swagger_client/api/task_controller_api'
require 'swagger_client/api/v2_canary_config_controller_api'
require 'swagger_client/api/v2_canary_controller_api'
require 'swagger_client/api/v2_pipeline_templates_controller_api'
require 'swagger_client/api/version_controller_api'
require 'swagger_client/api/webhook_controller_api'

module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
